// Generated by gencpp from file tledakbot_master/motion_cplt.msg
// DO NOT EDIT!


#ifndef ROBIT_MASTER_MESSAGE_MOTION_CPLT_H
#define ROBIT_MASTER_MESSAGE_MOTION_CPLT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ROBIT_master
{
template <class ContainerAllocator>
struct motion_cplt_
{
  typedef motion_cplt_<ContainerAllocator> Type;

  motion_cplt_()
    : motion_complete(false)  {
    }
  motion_cplt_(const ContainerAllocator& _alloc)
    : motion_complete(false)  {
  (void)_alloc;
    }



   typedef uint8_t _motion_complete_type;
  _motion_complete_type motion_complete;





  typedef boost::shared_ptr< ::ROBIT_master::motion_cplt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ROBIT_master::motion_cplt_<ContainerAllocator> const> ConstPtr;

}; // struct motion_cplt_

typedef ::ROBIT_master::motion_cplt_<std::allocator<void> > motion_cplt;

typedef boost::shared_ptr< ::ROBIT_master::motion_cplt > motion_cpltPtr;
typedef boost::shared_ptr< ::ROBIT_master::motion_cplt const> motion_cpltConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ROBIT_master::motion_cplt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ROBIT_master::motion_cplt_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ROBIT_master

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ROBIT_master': ['/home/robit/catkin_ws/src/ROBIT_master/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ROBIT_master::motion_cplt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROBIT_master::motion_cplt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROBIT_master::motion_cplt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROBIT_master::motion_cplt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROBIT_master::motion_cplt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROBIT_master::motion_cplt_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ROBIT_master::motion_cplt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fad2501533e9b0f7b45e5e434d99182e";
  }

  static const char* value(const ::ROBIT_master::motion_cplt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfad2501533e9b0f7ULL;
  static const uint64_t static_value2 = 0xb45e5e434d99182eULL;
};

template<class ContainerAllocator>
struct DataType< ::ROBIT_master::motion_cplt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ROBIT_master/motion_cplt";
  }

  static const char* value(const ::ROBIT_master::motion_cplt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ROBIT_master::motion_cplt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool motion_complete\n\
";
  }

  static const char* value(const ::ROBIT_master::motion_cplt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ROBIT_master::motion_cplt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motion_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motion_cplt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ROBIT_master::motion_cplt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ROBIT_master::motion_cplt_<ContainerAllocator>& v)
  {
    s << indent << "motion_complete: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motion_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBIT_MASTER_MESSAGE_MOTION_CPLT_H
